name: fals
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter
   # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 34 
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

     
  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/

      #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
